-- Create Email Logs Table
CREATE TABLE EMAIL_LOGS (
    ID NUMBER(19) PRIMARY KEY,
    RECIPIENT_EMAIL VARCHAR2(255) NOT NULL,
    SUBJECT VARCHAR2(500) NOT NULL,
    BODY CLOB,
    EMAIL_STATUS VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    ERROR_MESSAGE VARCHAR2(1000),
    SENT_AT TIMESTAMP,
    RETRY_COUNT NUMBER(10) DEFAULT 0,
    CC VARCHAR2(1000),
    BCC VARCHAR2(1000),
    USER_ID NUMBER(19),
    ORDER_ID NUMBER(19),
    INVOICE_ID NUMBER(19),
    PAYMENT_ID NUMBER(19),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(255),
    UPDATED_BY VARCHAR2(255),
    CONSTRAINT FK_EMAIL_LOG_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_EMAIL_LOG_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT FK_EMAIL_LOG_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(ID),
    CONSTRAINT FK_EMAIL_LOG_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS(ID)
);

-- Create sequence for Email Logs
CREATE SEQUENCE EMAIL_LOGS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create indexes for better query performance
CREATE INDEX IDX_EMAIL_LOGS_RECIPIENT ON EMAIL_LOGS(RECIPIENT_EMAIL);
CREATE INDEX IDX_EMAIL_LOGS_STATUS ON EMAIL_LOGS(EMAIL_STATUS);
CREATE INDEX IDX_EMAIL_LOGS_USER ON EMAIL_LOGS(USER_ID);
CREATE INDEX IDX_EMAIL_LOGS_SENT_AT ON EMAIL_LOGS(SENT_AT);
CREATE INDEX IDX_EMAIL_LOGS_RETRY ON EMAIL_LOGS(EMAIL_STATUS, RETRY_COUNT);

-- Add comments
COMMENT ON TABLE EMAIL_LOGS IS 'Email logs table - tracks all sent emails';
COMMENT ON COLUMN EMAIL_LOGS.RECIPIENT_EMAIL IS 'Recipient email address';
COMMENT ON COLUMN EMAIL_LOGS.EMAIL_STATUS IS 'Email status: PENDING, SENT, FAILED';
COMMENT ON COLUMN EMAIL_LOGS.RETRY_COUNT IS 'Number of retry attempts for failed emails';
